# Generated by Django 4.1.3 on 2022-11-02 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(default='none', max_length=50)),
                ('business_ID', models.CharField(default='none', max_length=50)),
                ('supportAgent_ID', models.CharField(default='none', max_length=50)),
                ('supportAgent', models.CharField(default='none', max_length=50)),
                ('addNoteName', models.CharField(default='none', max_length=500)),
                ('addNoteDetails', models.TextField(default='none')),
                ('Notetag', models.CharField(default='none', max_length=500)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(default='none', max_length=50)),
                ('branch_ID', models.CharField(default='none', max_length=50)),
                ('business_ID', models.CharField(default='none', max_length=50)),
                ('message_ID', models.CharField(default='none', max_length=50)),
                ('supportAgent', models.CharField(default='none', max_length=50)),
                ('userName', models.CharField(default='none', max_length=50)),
                ('country', models.CharField(default='none', max_length=20)),
                ('message', models.TextField()),
                ('phone', models.CharField(default='s-00', max_length=50)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
                ('supportMessage', models.BooleanField(default=False)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('media_type', models.CharField(default='none', max_length=20)),
                ('media_available', models.BooleanField(default=False)),
                ('message_is_opened', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(default='none', max_length=50)),
                ('branch_ID', models.CharField(default='none', max_length=50)),
                ('business_ID', models.CharField(default='none', max_length=50)),
                ('message_ID', models.CharField(default='none', max_length=50)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('media_file_url', models.URLField(default='')),
                ('media_type', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ListNavigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(default='none', max_length=50)),
                ('business_ID', models.CharField(default='none', max_length=50)),
                ('current_item', models.CharField(default='none', max_length=50)),
                ('phone', models.CharField(default='s-00', max_length=50)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Navigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(default='none', max_length=50)),
                ('business_ID', models.CharField(default='none', max_length=50)),
                ('current_page', models.CharField(default='none', max_length=50)),
                ('phone', models.CharField(default='s-00', max_length=50)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
