# Generated by Django 4.1.3 on 2022-11-02 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='None', max_length=50)),
                ('business_Name', models.CharField(default='None', max_length=50)),
                ('billing_Name', models.CharField(default='None', max_length=50)),
                ('emailCounter', models.IntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('first_billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('second_billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('third_billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('forth_billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_suspension_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_billing_status', models.BooleanField(default=False)),
                ('second_billing_status', models.BooleanField(default=False)),
                ('third_billing_status', models.BooleanField(default=False)),
                ('forth_billing_status', models.BooleanField(default=False)),
                ('suspend_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instance_ID', models.CharField(default='None', max_length=50)),
                ('Instance_IP', models.CharField(max_length=50)),
                ('Port', models.CharField(default='---', max_length=250)),
                ('instanceUser', models.CharField(default='None', max_length=250)),
                ('instancePassword', models.CharField(default='None', max_length=250)),
                ('SSH_Key', models.CharField(default='None', max_length=250)),
                ('assinged_status', models.BooleanField(default=False)),
                ('portal_installed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPortalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instance_ID', models.CharField(default='None', max_length=50)),
                ('Instance_IP', models.CharField(default='None', max_length=50)),
                ('School_name', models.CharField(default='None', max_length=250)),
                ('school_ID', models.CharField(max_length=50)),
                ('Port', models.CharField(default='---', max_length=250)),
                ('Instance_assinged_status', models.BooleanField(default=False)),
                ('BillingAccount_active_status', models.BooleanField(default=False)),
                ('config_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ApiCofig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_Name', models.CharField(default='none', max_length=500)),
                ('school_ID', models.CharField(default='none', max_length=500)),
                ('apiUrl1', models.CharField(default='http//', max_length=400)),
                ('apiUrl2', models.CharField(default='http//', max_length=400)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_active_status', models.BooleanField(default=False)),
                ('setup_ready', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
